### ISSUE TITLE
Update rubocop Metrics/ModuleLength from 100 to 200

### ISSUE THREAD

**Issue by vinfante** [wizeline/ror-remotepayment-wizeline#100]
So to allow longer Module Length

Suggested solution:

.rubocop.yml
```
Metrics/ModuleLength:
  Description: "Avoid classes longer than 200 lines of code"
  Enabled: true
  Max: 200
```
